services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - '3000:80'
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:80/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Local development - no Traefik labels needed
